/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aran_e.h_shop;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek
 */
public class creditcard extends javax.swing.JFrame {

    /**
     * Creates new form creditcard
     */
    public creditcard() {
        initComponents();
        try{
          Class.forName("java.sql.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abhielectronics","root","abhishek28");
        Statement stmt2=con.createStatement();
          String query2="Select * from active;";
          ResultSet rs2=stmt2.executeQuery(query2);
          while(rs2.next()){
              String user=rs2.getString(1);
          Statement stmt1=con.createStatement();
          String query1="Select sum(price) from products where user='"+user+"';";
          ResultSet rs1=stmt1.executeQuery(query1);
          while(rs1.next()){
          int tot=rs1.getInt(1);
          jLabel3.setText("Rs "+Integer.toString(tot));
          }}
      }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aran_e/h_shop/Newpic-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(443, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1039, 189);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Checkout");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(470, 200, 140, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Credit Card Payment");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 240, 170, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 280, 110, 20);

        jButton1.setText("  Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 420, 80, 23);

        jLabel5.setText("*Items will be delivered in 6-8 working days.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 460, 260, 14);

        jLabel2.setText("Total Price:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 280, 70, 14);

        jLabel4.setText("Address:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 320, 60, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 320, 490, 20);

        jLabel6.setText("Credit card No.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 370, 90, 14);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(130, 370, 40, 20);

        jLabel7.setText("-");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 370, 4, 14);

        jLabel8.setText("-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(260, 370, 4, 14);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 370, 40, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(350, 370, 40, 20);

        jLabel9.setText("-");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 370, 4, 14);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(280, 370, 40, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/pokas.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 170, 1290, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        int length = String.valueOf(Integer.parseInt(jTextField2.getText())).length();
int length1 = String.valueOf(Integer.parseInt(jTextField3.getText())).length();
int length2 = String.valueOf(Integer.parseInt(jTextField4.getText())).length();
int length3 = String.valueOf(Integer.parseInt(jTextField5.getText())).length();
        if(jTextField1.getText().equals("")){
        JOptionPane.showMessageDialog(this,"Please enter address");
        }
        else if(length!=4||length1!=4||length2!=4||length3!=4){
            JOptionPane.showMessageDialog(this,"Please enter correct number of digits");
            }
else{
try{
          Class.forName("java.sql.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abhielectronics","root","abhishek28");
          Statement stmt2=con.createStatement();
          String query2="Select * from active;";
          ResultSet rs2=stmt2.executeQuery(query2);
          while(rs2.next()){
              String user=rs2.getString(1);
              Statement stmt1=con.createStatement();
          String query1="Select item from products where user='"+user+"';";
          ResultSet rs1=stmt1.executeQuery(query1);
          while(rs1.next()){
              String item=rs1.getString(1);
              Statement stmt=con.createStatement();
          String query="Update product set qty=qty-1 where name='"+item+"';";
          stmt.executeUpdate(query);
          }
          Statement stmt=con.createStatement();
          String query="Delete from products where user='"+user+"';";
          stmt.executeUpdate(query);
                  }}catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
            JOptionPane.showMessageDialog(this,"Your items will be delivered within the specified time given");
            this.setVisible(false);
            new main1().setVisible(true);}
}catch(Exception e){
    JOptionPane.showMessageDialog(this,"Please fill in all places for the credit card number");
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creditcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creditcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creditcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creditcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creditcard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
